from .address import Address
from .assignment import Assignment
from .assignmentGroup import AssignmentGroup
from .attendanceReason import AttendanceReason
from .authentication import Authentication
from .branch import Branch
from .grade import Grade
from .organisation import Organisation
from .relationType import RelationType
from .role import Role
from .room import Room
from .studentClass import StudentClass
from .userGroup import UserGroup
from .user import User

from .branchAddress import BranchAddress
from .groupUser import UserGroup
from .userAddress import UserAddress
from .userBranch import UserBranch
from .userGroupStudentClass import UserGroupStudentClass
from .userGroupUser import UserGroupUser
from .userOrganisation import UserOrganisation
from .userRelation import UserRelation
from .userRole import UserRole
from .userStudentClass import UserStudentClass
